@host=http://localhost:5023

GET {{host}}/packages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMGJjNTU4NS04MzY5LTQ5OGItYWJjMy1lNTViZmI5MDRhZWUiLCJnaXZlbl9uYW1lIjoiQW5kcmlhbiIsImZhbWlseV9uYW1lIjoiR2FpZGFyamkiLCJqdGkiOiI5ODM0MDM5YS0yNTI4LTQ3ZDQtODQ4MC01ODI2YzI0OTI4YTciLCJleHAiOjE2ODQwMjMwNjIsImlzcyI6Ik9yaW9uIiwiYXVkIjoiT3Jpb24ifQ.pr_maSHN2jLIucZSKRrCqK8UiBTl8Vb5MazKku_db9A